name: Make Packages on Push

on:
  push:
  pull_request:

jobs:
  make-package:
    strategy:
      matrix:
        package:
          - xyz.misakal.vpm.yes-patch-framework-for-sdk
          - xyz.misakal.vpm.yet-another-sdk-patch
          - xyz.misakal.vpm.yet-another-sdk-patch.avatars
          - xyz.misakal.vpm.yet-another-sdk-patch.worlds

    uses: ./.github/workflows/make-package.yml
    with:
      ref: ${{ github.ref_name }}
      package: ${{ matrix.package }}
